### ISSUE TITLE
Example code error

### ISSUE THREAD

**Issue by gizemcaylak** [BorgwardtLab/Multi-SConES#1]
Hi,
When I run the example code provided in README.md, at `res <- mscones(g = g, X = X, Y = Y)` it gives the error:
```
Post-processing ... Error in as.igraph.vs(graph, vids) : 
  Cannot use a vertex sequence from another graph.
```

Could you please check this? Thanks.

**Comment by mahito-sugiyama** [comment]
Thank you very much for pointing this out!
This bug is due to the update of the igraph package. Now I have fixed and updated the code.
